### ISSUE TITLE
Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')

### ISSUE THREAD

**Issue by 01choco** [TimeForANinja/node-ytsr#181] opened 2023-02-20 13:47 UTC
I am making music player bot, and this error crushed.
want to know how to solve this problem.. 
[mtxttc29hm-1676900691501.txt](https://github.com/TimeForANinja/node-ytsr/files/10785004/mtxttc29hm-1676900691501.txt)

**Comment by RisedSky** [comment] 2023-02-20 19:18
i have the same error

**Comment by ArmyaAli** [comment] 2023-02-20 19:25
Smae

**Comment by Matix2021** [comment] 2023-02-21 20:43
Same

**Comment by rablonkk** [comment] 2023-02-23 22:52
I had the same error, but to solve this problem, I had to use a modified version of ytsr, and it's working fine!

if you want to install, just use this repository:
https://github.com/Yonle/node-ytsr/

installing using npm or yarn is easy, just add .git at the end of the repository.

example:
npm install https://github.com/Yonle/node-ytsr.git (using npm)
yarn add https://github.com/Yonle/node-ytsr.git (using yarn)

**Comment by lupus0802** [comment] 2023-02-24 15:06
I'm also having this issue, however, the request still returns with a result. I'll try the solution by @rablonkk.

**Comment by ArmyaAli** [comment] 2023-02-24 17:01
Switching to a fork of the library maintained by someone else, isn't really a solution lol ^^ but it is good if you want a quick resolution

**Comment by rablonkk** [comment] 2023-02-24 22:16
it may not even be a definitive solution, but it can help us in a short period of time. while the problem is not solved definitively.

**Comment by idoob** [comment] 2023-02-26 18:43
It seems like a handful people have asked in the support Discord for a review on pending PRs without success. Although it's not ideal, if this issue is blowing up your logs you can override `ytsr` in your dependencies with @Yonle's fork which includes these fixes. 

Here's an example of what I did with NPM. 

```
// package.json
{
   ...
  "overrides": {
    "ytsr": "github:Yonle/node-ytsr"
},
```

Not a great long-term fix but at least it prevents logs from blowing up with the errors.

**Comment by ArmyaAli** [comment] 2023-02-26 20:20
> It seems like a handful people have asked in the support Discord for a review on pending PRs without success. Although it's not ideal, if this issue is blowing up your logs you can override `ytsr` in your dependencies with @Yonle's fork which includes these fixes.
> 
> Here's an example of what I did with NPM.
> 
> ```
> // package.json
> {
>    ...
>   "overrides": {
>     "ytsr": "github:Yonle/node-ytsr"
> },
> ```
> 
> Not a great long-term fix but at least it prevents logs from blowing up with the errors.

Hey that's pretty neat with the overrides, thanks for this

**Comment by TimeForANinja** [comment] 2023-03-29 16:14
dupe of #174 
still thanks for opening 👍

**Closed by TimeForANinja** 2023-03-29 16:14 UTC
