### ISSUE TITLE
Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')

### ISSUE THREAD

**Issue by eckshton** [TimeForANinja/node-ytsr#179] opened 2023-02-03 01:00 UTC
TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (D:\music bot\node_modules\ytsr\lib\parseItem.js:355:67)
    at parseItem (D:\music bot\node_modules\ytsr\lib\parseItem.js:28:14)
    at D:\music bot\node_modules\ytsr\lib\parseItem.js:409:30
    at Array.map (<anonymous>)
    at parseShelf (D:\music bot\node_modules\ytsr\lib\parseItem.js:409:21)
    at parseItem (D:\music bot\node_modules\ytsr\lib\parseItem.js:32:14)
    at catchAndLogFunc (D:\music bot\node_modules\ytsr\lib\parseItem.js:88:12)
    at module.exports (D:\music bot\node_modules\ytsr\lib\parseItem.js:111:46)
    at D:\music bot\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)

failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in D:\music bot\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v18.13.0, ytsr: 3.8.0

[qn92kvubti-1675385469493.txt](https://github.com/TimeForANinja/node-ytsr/files/10574593/qn92kvubti-1675385469493.txt)

**Comment by RyantheSheriff** [comment] 2023-02-16 04:39
Same issue here, whats up with this

**Comment by megaf1re** [comment] 2023-02-16 06:14
I have the same problem

**Comment by Bebiezaza** [comment] 2023-02-18 06:50
My application's internal logger is getting dumped on by this message! It is literally unreadable at this point.

**Comment by RisedSky** [comment] 2023-02-20 19:18
i have the same error

**Comment by TimeForANinja** [comment] 2023-03-29 16:16
dupe of #174 
still thanks for opening 👍

**Closed by TimeForANinja** 2023-03-29 16:16 UTC
